apiVersion: v1
kind: ConfigMap
metadata:
  name: relay
  labels:
    app: relay
data:
  config.yml: |-
    relay:
      mode: managed
      upstream: "http://sentry-web:{{ .Values.service.externalPort }}/"
      host: 0.0.0.0
      port: 3000
    processing:
      enabled: true
      {{- if .Values.geodata.path }}
      geoip_path: {{ .Values.geodata.path | quote }}
      {{- end }}
      kafka_config:
        - name: "bootstrap.servers"
          value: {{ (include "sentry.kafka.bootstrap_servers_string" .) | quote }}
        - name: "message.max.bytes"
          value: 50000000  # 50MB or bust
      redis: "redis://{{ template "redis.fullname" . }}:6379"
