apiVersion: v1
kind: ConfigMap
metadata:
  name: relay
  labels:
    app: relay
data:
  config.yml: |-
    relay:
      mode: proxy
      upstream: "https://{{ .Values.ingress.host }}/"
    processing:
      enabled: true
      kafka_config:
        - name: "bootstrap.servers"
          value: {{ (include "sentry.kafka.bootstrap_servers_string" .) | quote }}
        - name: "message.max.bytes"
          value: 50000000  # 50MB or bust
      redis: "redis://{{ template "redis.fullname" . }}:6379"
