apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-cron
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-cron
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-cron
        alert-tier: os
        alert-service: sentry
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{required ".Values.global.registry is missing" .Values.global.registry }}/{{ .Values.image.sentry.repository }}:{{required ".Values.image.sentry.tag is missing" .Values.image.sentry.tag }}"
        imagePullPolicy: {{ .Values.image.sentry.pullPolicy }}
        args: [ run, cron ]
        env:
{{ include "env-vars" . | indent  10 }}
