apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-snuba-outcomes-consumer
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "17"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-outcomes-consumer
  replicas: {{ .Values.snuba.outcomesConsumer.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.outcomesConsumer.annotations }}
{{ toYaml .Values.snuba.outcomesConsumer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-outcomes-consumer
        {{- if .Values.snuba.outcomesConsumer.podLabels }}
{{ toYaml .Values.snuba.outcomesConsumer.podLabels | indent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{required ".Values.global.dockerHubMirror is missing" .Values.global.dockerHubMirror }}/{{ .Values.image.snuba.repository }}:{{required ".Values.image.snuba.tag is missing" .Values.image.snuba.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.snuba.pullPolicy }}
        command:
          - "snuba"
          - "consumer"
          - "--storage"
          - "outcomes_raw"
          - "--auto-offset-reset"
          - "{{ .Values.snuba.outcomesConsumer.autoOffsetReset }}"
          - "--max-batch-size"
          - "{{ default "3" .Values.snuba.outcomesConsumer.maxBatchSize }}"
          {{- if .Values.snuba.outcomesConsumer.processes }}
          - "--processes"
          - "{{ .Values.snuba.outcomesConsumer.processes }}"
          {{- end }}
          {{- if .Values.snuba.outcomesConsumer.inputBlockSize }}
          - "--input-block-size"
          - "{{ .Values.snuba.outcomesConsumer.inputBlockSize }}"
          {{- end }}
          {{- if .Values.snuba.outcomesConsumer.outputBlockSize }}
          - "--output-block-size"
          - "{{ .Values.snuba.outcomesConsumer.outputBlockSize }}"
          {{- end }}
          {{- if .Values.snuba.outcomesConsumer.maxBatchTimeMs }}
          - "--max-batch-time-ms"
          - "{{ .Values.snuba.outcomesConsumer.maxBatchTimeMs }}"
          {{- end }}
          {{- if .Values.snuba.outcomesConsumer.queuedMaxMessagesKbytes }}
          - "--queued-max-messages-kbytes"
          - "{{ .Values.snuba.outcomesConsumer.queuedMaxMessagesKbytes }}"
          {{- end }}
          {{- if .Values.snuba.outcomesConsumer.queuedMinMessages }}
          - "--queued-min-messages"
          - "{{ .Values.snuba.outcomesConsumer.queuedMinMessages }}"
          {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.outcomesConsumer.env }}
{{ toYaml .Values.snuba.outcomesConsumer.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "fullname" . }}-snuba-env
        resources:
{{ toYaml .Values.snuba.outcomesConsumer.resources | indent 12 }}
