{{- if .Values.symbolicator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-symbolicator-api
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: "{{ .Release.Name }}"
      role: symbolicator-api
{{- if not .Values.symbolicator.api.autoscaling.enabled }}
  replicas: {{ .Values.symbolicator.api.replicas }}
{{- end }}
  template:
    metadata:
      annotations:
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-symbolicator.yaml") . | sha256sum }}
        {{- if .Values.symbolicator.api.annotations }}
{{ toYaml .Values.symbolicator.api.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
        role: symbolicator-api
        {{- if .Values.symbolicator.api.podLabels }}
{{ toYaml .Values.symbolicator.api.podLabels | indent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-symbolicator
        image: "{{ template "symbolicator.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.symbolicator.pullPolicy }}
        args: ["run", "-c", "/etc/symbolicator/config.yml"]
        ports:
        - containerPort: {{ template "symbolicator.port" }}
        env:
{{ include "env-vars" . | indent  10 }}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthcheck
            port: {{ template "symbolicator.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.symbolicator.api.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthcheck
            port: {{ template "symbolicator.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.symbolicator.api.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
