apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-relay
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "25"
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: "{{ .Release.Name }}"
      role: relay
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      annotations:
        checksum/relay: {{ .Values.config.relay | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-relay.yaml") . | sha256sum }}
        {{- if .Values.relay.annotations }}
{{ toYaml .Values.relay.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
        role: relay
        {{- if .Values.relay.podLabels }}
{{ toYaml .Values.relay.podLabels | indent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-relay-init
          image: "{{required ".Values.global.dockerHubMirror is missing" .Values.global.dockerHubMirror }}/{{ .Values.image.relay.repository }}:{{required ".Values.image.relay.tag is missing" .Values.image.relay.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.relay.pullPolicy }}
          args:
            - "credentials"
            - "generate"
          env:
            - name: RELAY_PORT
              value: '{{ template "relay.port" }}'
          volumeMounts:
            - name: credentials
              mountPath: /work/.relay
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-relay
        image: "{{required ".Values.global.dockerHubMirror is missing" .Values.global.dockerHubMirror }}/{{ .Values.image.relay.repository }}:{{required ".Values.image.relay.tag is missing" .Values.image.relay.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.relay.pullPolicy }}
        ports:
        - containerPort: {{ template "relay.port" }}
        env:
        - name: RELAY_PORT
          value: '{{ template "relay.port" }}'
{{- if .Values.relay.env }}
{{ toYaml .Values.relay.env | indent 8 }}
{{- end }}
        volumeMounts:
          - name: credentials
            mountPath: /work/.relay
          {{- if .Values.geodata.volumeName }}
          - name: {{ .Values.geodata.volumeName }}
            mountPath: {{ .Values.geodata.mountPath }}
          {{- end }}
        livenessProbe:
          failureThreshold: {{ .Values.relay.probeFailureThreshold }}
          httpGet:
            path: {{ template "relay.healthCheck.livenessRequestPath" }}
            port: {{ template "relay.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.relay.probeInitialDelaySeconds }}
          periodSeconds: {{ .Values.relay.probePeriodSeconds }}
          successThreshold: {{ .Values.relay.probeSuccessThreshold }}
          timeoutSeconds: {{ .Values.relay.probeTimeoutSeconds }}
        readinessProbe:
          failureThreshold: {{ .Values.relay.probeFailureThreshold }}
          httpGet:
            path: {{ template "relay.healthCheck.readinessRequestPath" }}
            port: {{ template "relay.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.relay.probeInitialDelaySeconds }}
          periodSeconds: {{ .Values.relay.probePeriodSeconds }}
          successThreshold: {{ .Values.relay.probeSuccessThreshold }}
          timeoutSeconds: {{ .Values.relay.probeTimeoutSeconds }}
      volumes:
      - name: credentials
        emptyDir: {}
{{- if .Values.relay.volumes }}
{{ toYaml .Values.relay.volumes | indent 6 }}
{{- end }}
