apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-pruning
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-pruning
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-pruning
        alert-tier: os
        alert-service: sentry
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{required ".Values.global.dockerHubMirror is missing" .Values.global.dockerHubMirror }}/{{ .Values.image.sentry.repository }}:{{required ".Values.image.sentry.tag is missing" .Values.image.sentry.tag }}"
        imagePullPolicy: {{ .Values.image.sentry.pullPolicy }}
        command: [sh]
        args:
          - -ec
          - |
            while true; do
              if [ $(date '+%H%M') = '{{ .Values.pruning_time }}' ]; then
                sentry cleanup --days 7
              fi
              sleep 55
            done 
        env:
{{ include "env-vars" . | indent  10 }}
