apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.serverReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        alert-tier: os
        alert-service: sentry
    spec:
      containers:
      - name: {{ .Chart.Name }}-web
        image: "{{required ".Values.global.registry is missing" .Values.global.registry }}/{{ .Values.image.sentry.repository }}:{{required ".Values.image.sentry.tag is missing" .Values.image.sentry.tag }}"
        args: [ run, web ]
        #command: [tail, -f, /dev/null]
        imagePullPolicy: {{ .Values.image.sentry.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /_health/
            port: {{ .Values.service.internalPort }}
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /_health/
            port: {{ .Values.service.internalPort }}
          timeoutSeconds: 5
        env:
{{ include "env-vars" . | indent  10 }}
