apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.serverReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        alert-tier: os
        alert-service: sentry
    spec:
      containers:
      - name: {{ .Chart.Name }}-web
        image: "{{required ".Values.global.registry is missing" .Values.global.registry }}/{{ .Values.image.sentry.repository }}:{{required ".Values.image.sentry.tag is missing" .Values.image.sentry.tag }}"
        args: [ run, web ]
        #command: [tail, -f, /dev/null]
        imagePullPolicy: {{ .Values.image.sentry.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /_health/
            port: {{ .Values.service.internalPort }}
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /_health/
            port: {{ .Values.service.internalPort }}
          timeoutSeconds: 5
        env:
{{ include "env-vars" . | indent  10 }}
{{- if .Values.nginx.enabled }}
      - name: nginx
        image: {{ .Values.global.dockerHubMirror | required ".Values.global.dockerHubMirror is missing" }}/library/{{ .Values.nginx.image }}:{{ .Values.nginx.image_version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: nginx-etc
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
        ports:
          - name: http
            containerPort: {{ .Values.nginx.port.public }}
            protocol: TCP
        resources:
          requests:
            memory: "50Mi"
            cpu: "150m"
          limits:
            memory: "50Mi"
            cpu: "150m"
      volumes:
      - name: nginx-etc
        configMap:
          name: nginx-etc
          defaultMode: 0644
{{- end }}
