{{- if .Values.thanos.enabled }}
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: {{ include "prometheus.fullName" . }}-thanos-store
spec:
  storeGateway:
    httpAddress: 0.0.0.0:{{ required ".Values.thanos.querier.service.httpPort missing" .Values.thanos.querier.service.httpPort }}
    grpcAddress: 0.0.0.0:{{ required ".Values.thanos.querier.service.grpcPort missing" .Values.thanos.querier.service.grpcPort }}
    logLevel: {{ .Values.logLevel }}
    indexCacheSize: {{ required ".Values.thanos.store.indexCacheSize missing" .Values.thanos.store.indexCacheSize }}
    chunkPoolSize: {{ required ".Values.thanos.store.chunkPoolSize missing" .Values.thanos.store.chunkPoolSize }}
    # storeGRPCSeriesSampleLimit: {{ required ".Values.thanos.store.seriesSampleLimit missing" .Values.thanos.store.seriesSampleLimit | quote }}
    storeGRPCSeriesMaxConcurrency: {{ required ".Values.thanos.store.seriesMaxConcurrency missing" .Values.thanos.store.seriesMaxConcurrency }}
    # metaOverrides:
      # name: {{ include "prometheus.fullName" . }}-thanos
    deploymentOverrides:
      spec:
        template:
          spec:
            containers:
            - image: keppel.eu-de-1.cloud.sap/ccloud-quay-mirror/thanos/thanos:v0.26.0
              name: store
{{ end }}
