{{- if .Values.thanos.enabled }}
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: StoreEndpoint
metadata:
  name: {{ include "prometheus.fullName" . }}-thanos
spec:
  thanos: {{ include "prometheus.fullName" . }}-thanos-store
  # url: http://thanos.{{ required ".Values.global.region" .Values.global.region }}.{{ required ".Values.global.tld" .Values.global.tld }}
  config:
    mountFrom:
      secretKeyRef:
        name: {{ include "thanos.objectStorageConfig.name" . }}
        key: thanos.yaml
{{ end }}
