# Declare variables to be passed into your templates.
cc3test:
  namespace: cc3test
  image:
    name: cc3test
    tag: DEFINED-IN-PIPELINE
prometheus:
  pushgateway: DEFINED-IN-SECRETS
alerts:
  enabled: true
  prometheus: infra-frontend
owner-info:
  support-group: observability
  maintainers:
    - Abhishek Kumar
    - Martin Vossen
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/openstack/cc3test
