apiVersion: v2
description: Prometheus operator via kube-prom-stack
name: prometheus-operator
version: 1.0.0
home: https://github.com/sapcc/helm-charts/tree/master/system/prometheus-operator
dependencies:
  - name: prometheus-crds
    repository: https://charts.eu-de-2.cloud.sap
    version: 4.0.0
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 39.0.0
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
