{{- if .Values.enabled }}
{{- if .Values.useQueryRegions }}
apiVersion: v1
kind: Secret

metadata:
  name: thanos-grpcclient-crt

data:
  tls.crt: {{ required ".Values.GRPClientCertificate.certificate missing" .Values.GRPCClientCertificate.certificate | b64enc | quote }}
  tls.key: {{ required ".Values.GRPClientCertificate.privateKey missing" .Values.GRPCClientCertificate.privateKey | b64enc | quote }}
{{ end }}
{{ end }}