{{- if ne .Values.global.region "ap-sa-2" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-nova-pvclaim
  labels:
    ccloud/support-group: compute-storage-api
    ccloud/service: nova
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
{{- end }}
