---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kvm-shared1-pvclaim
  labels:
    ccloud/support-group: compute-storage-api
    ccloud/service: nova
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
