apiVersion: v2
description: nannies - taking care of leftovers and inconsistencies from daily operations
name: nannies
version: 0.1.0
dependencies:
  - name: utils
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.3.0
