owner-info:
  support-group: compute
  maintainers:
    - Christopher Hans
    - Maximilian Lendrich
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/tarslite
tarslite:
  image:
    registry: DEFINED-IN-REGION-SECRETS
    name: tarslite
  enabled: false
  webhook:
    host: localhost
    port: 9496
  awx:
    host: DEFINED-IN-REGION-SECRETS
    token: DEFINED-IN-REGION-SECRETS
  slack:
    token: DEFINED-IN-REGION-SECRETS
    workspace: DEFINED-IN-REGION-SECRETS
    info: DEFINED-IN-REGION-SECRETS
    warning: DEFINED-IN-REGION-SECRETS
    critical: DEFINED-IN-REGION-SECRETS
    channel: DEFINED-IN-REGION-SECRETS
