apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name:  prometheus-vrops-inventory-exporters
  labels:
    prometheus: {{ .Values.vrops.prometheusName }}

spec:
  jobLabel: vrops-inventory-exporter

  selector:
    matchLabels:
      target: vrops-inventory-exporter

  namespaceSelector:
    matchNames: [{{ required ".Values.vrops.namespace variable missing" .Values.vrops.namespace }}]

  podMetricsEndpoints:
    - interval: 60s
      scrapeTimeout: 50s
      path: /metrics
      scheme: http
      port: metrics
      relabelings:
        - targetLabel: job
          replacement: vrops-inventory-exporter
      metricRelabelings:
        - action: labeldrop
          regex: "container|instance|endpoint|pod|namespace|service"
