{{- if .Values.manila_nanny.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: manila-nanny-secret
  labels:
    ccloud/support-group: compute-storage-api
    ccloud/service: manila
data:
  {{- if ne .Values.nannies.manila_netapp_username "DEFINED-IN-REGION-CHART"}}
  manila_netapp_api_username: {{ .Values.nannies.manila_netapp_username | b64enc }}
  manila_netapp_api_password: {{ .Values.nannies.manila_netapp_password | b64enc }}
  {{- else }}

  {{- with (first .Values.global.netapp.filers)}}
  manila_netapp_api_username: {{ .username | b64enc }}
  manila_netapp_api_password: {{ .password | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
