apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-map
data:
  app-environment: {{ .Values.env.APP_ENVIRONMENT | default "slackcloud"}}
  slack-workspace: {{ .Values.env.SLACK_WORKSPACE | default "convergedcloud"}}