apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  slack-app-config-token: {{ required "env.SLACK_APP_CONFIG_TOKEN needs to be set" .Values.env.SLACK_APP_CONFIG_TOKEN | b64enc }}
  slack-refresh-token: {{ required "env.SLACK_REFRESH_TOKEN needs to be set" .Values.env.SLACK_REFRESH_TOKEN | b64enc }}
  github-token: {{ required "env.GITHUB_TOKEN needs to be set" .Values.env.GITHUB_TOKEN | b64enc }}