thanos:
  name: metal
  deployWholeThanos: false
  ingress:
    enabled: true
    hosts:
      - thanos-metal
      - metrics.metal
      - prometheus-vmware
  grpcIngress:
    enabled: true
    hosts:
      - thanos-metal
  queryDiscovery: true
