global:
  tld: cloud.sap
  region: local
# specify the k8s keystone namespace if it differs from the current chart
  keystoneNamespace: monsoon3
  imageNamespace: monsoon
  user_suffix: ""

custom_configmap: false
## if custom repository is enabled it takes global/imageRegistry and global/imageNamespace
custom_repository: false

extensions:
  pg_stat_statements:
    max: 1000
    track: all

## postgres image repository
image: "postgres"
## postgres image version
## ref: https://hub.docker.com/r/library/postgres/tags/
##
imageTag: "9.5.4"

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

## Create a database user
## Default: postgres
postgresUser: postgres
## Default: random 10 character string
# postgresPassword:

## Create a database
## Default: the postgres user
# postgresDatabase:

# custom db-init.sh
# dbInit: name of a configmap that provides the db-init.sh script

# custom db-maintain.sh
# dbMaintain: name of a configmap that provides the db-maintain.sh script

hba_cidr: 0.0.0.0/0
auth_method: password

# Sets the option of the same name in the postgresql.conf. If set to a positive
# integer value, logs statements that run for longer than this many
# milliseconds.
log_min_duration_statement: -1

## Persist data to a persitent volume
persistence:
  enabled: false
  accessMode: ReadWriteMany
  size: 10Gi
  # Re-use existing (unmanged) PVC
  # existingClaim: claimName

probe_timeout_secs: 3

replicas: 1

pod:
  lifecycle:
    upgrades:
      deployments:
        revision_history: 5
        pod_replacement_strategy: "RollingUpdate"
        rolling_update:
          max_unavailable: 1
          max_surge: 0

upgrades:
  revisionHistory: 3
  podReplacementStrategy: Recreate
## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}

backup:
  enabled: false
  image: monsoon/backup-tools
  imageTag: v0.5.15
  interval_full: 1 hours
#  os_auth_url: DEFINED-IN-REGION-SECRETS
#  os_region_name: DEFINED-IN-REGION-SECRETS
  os_password: DEFINED-IN-REGION-SECRETS
  os_username: db_backup
  os_user_domain: Default
  os_project_name: master
  os_project_domain: ccadmin

  # if custom repository is enabled, .Values.backup.image must be the full
  # repository URL; .Values.global.imageRegistry is not prepended
  custom_repository: false

  resources:
    enabled: true
    limits:
      memory: 192Mi
      cpu: 100m
    requests:
      memory: 192Mi
      cpu: 100m

cdc:
  enabled: false

# Default Prometheus alerts and rules.
alerts:
  enabled: true

  # Name of the Prometheus supposed to scrape the metrics and to which alerts are assigned.
  prometheus: openstack
  # Name of the Prometheus containing the disk usage metrics.
  prometheus_for_disk_usage: kubernetes

  # The tier label of the alerts.
  tier: os
  # The support group label of the alerts. Must be given in values.yaml of parent chart.
  support_group:

  # Configurable service label of the alerts. Defaults to `.Release.Name`.
  # service:
