{{- range $path, $bytes := $.Files.Glob "aggregations/*.rules" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ printf "vmware-%s" $path | replace "/" "-" }}
  labels:
    prometheus: {{ $.Values.prometheusName }}

spec:
{{ printf "%s" $bytes | indent 2 }}

{{- end }}