apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkPodSecurity
metadata:
  name: podsecurity
  labels:
    on-prod-ui: 'false' # TODO: enable once the allowlists are sufficiently fleshed out
spec:
  enforcementAction: dryrun
  match: {{ include "match_pods_and_pod_owners" . | indent 4 }}
