{{- if or .Release.IsInstall .Release.IsUpgrade }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "region_check.fullname" . }}
  labels:
    system: openstack
    type: configuration
    app.kubernetes.io/name: {{ include "region_check.name" . }}
    helm.sh/chart: {{ include "region_check.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-weight": "-1000"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
data:
{{- $nodes := lookup "v1" "Node" "" "" }}
{{- if not $nodes }}
  node: "no-nodes, likely template, or dry-run run"
{{- else }}
{{- $node := $nodes.items | mustFirst }}
    {{- $suffix := print (.Values.global.region | required "Missing .Values.global.region") "." (.Values.global.tld | required "Missing .Values.global.region") }}
    {{- if hasSuffix $suffix $node.metadata.name }}
  node: "{{ $node.metadata.name }}"
    {{- else }}
        {{ fail (print "Wrong region/domain " $suffix " for host " $node.metadata.name) }}
    {{- end }}
{{- end }}
{{- end }}
