{{- if .Values.thanos.enabled }}
{{- $root := . }}
{{- range $name := coalesce .Values.names .Values.global.targets (list .Values.name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus.fullName" (list $name $root) }}-thanos-storage-config
  labels:
    prometheus: {{ include "prometheus.name" (list $name $root) }}

data:
  {{ include "thanos.objectStorageConfig.key" $root }}: {{ include (print $.Template.BasePath  "/thanos/_thanos.yaml.tpl") (list $name $root) | b64enc }}
{{- end }}
{{- end }}
