{{- $root := . }}
{{- if and .Values.thanos.enabled .Values.thanos.seed.enabled }}
{{- range $name := coalesce .Values.names .Values.global.targets (list .Values.name) }}
---
apiVersion: "openstack.stable.sap.cc/v1"
kind: OpenstackSeed
metadata:
  name: {{ include "prometheus.name" (list $name $root) }}-thanos
  labels:
    prometheus: {{ include "prometheus.name" (list $name $root) }}

spec:
  {{ if $.Values.thanos.seed.requires }}
  requires:
{{ toYaml $.Values.thanos.seed.requires | indent 4 }}
  {{ end }}

  domains:
    - name: {{ required "$.Values.thanos.swiftStorageConfig.userDomainName missing" $.Values.thanos.swiftStorageConfig.userDomainName }}
      users:
        - name: {{ include "prometheus.fullName" (list $name $root) }}-thanos
          description: Thanos Service User
          password: {{ required "$.Values.thanos.swiftStorageConfig.password missing" $.Values.thanos.swiftStorageConfig.password | quote }}
          role_assignments:
            - project: service
              role:    service

    - name: {{ required "$.Values.thanos.swiftStorageConfig.domainName missing" $.Values.thanos.swiftStorageConfig.domainName }}
      projects:
        - name: {{ include "thanos.projectName" $root }}
          role_assignments:
            # Read/write permission to $domain/$project containers.
            - user: {{ include "prometheus.fullName" (list $name $root) }}-thanos@{{ required "$.Values.thanos.swiftStorageConfig.userDomainName missing" $.Values.thanos.swiftStorageConfig.userDomainName }}
              role: objectstore_admin
          swift:
            containers:
              - name: {{ include "prometheus.fullName" (list $name $root) }}-thanos
{{- end }}
{{- end }}
