thanos:
  name: virtual
  deployWholeThanos: false
  ingress:
    enabled: true
    hosts:
      - thanos-virtual
      - metrics.virtual
  grpcIngress:
    enabled: true
    hosts:
      - thanos-virtual
  queryDiscovery: true
