apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: gkdeprecatedapiversion
spec:
  crd:
    spec:
      names:
        kind: GkDeprecatedApiVersion
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            helmManifestParserURL:
              type: string
            kubernetesVersion:
              type: string
            apiVersions:
              type: array
              items:
                type: string

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package deprecatedapiversion

        iro := input.review.object

        parser_url := sprintf("%s/v3", [input.parameters.helmManifestParserURL])
        parser_resp := http.send({"url": parser_url, "method": "POST", "raise_error": false, "raw_body": iro.data.release, "timeout": "15s"})

        violation[{"msg": msg, "details": {"name": obj.metadata.name, "kind": obj.kind}}] {
          # must be a Helm 3 release
          iro.kind == "Secret"
          iro.type == "helm.sh/release.v1"
          iro.metadata.labels.status == "deployed"

          # release manifest must have been parsed successfully
          parser_resp.status_code == 200

          # find objects in the manifest that use deprecated API versions
          obj := parser_resp.body.items[_]
          input.parameters.apiVersions[_] == obj.apiVersion
          owner_info := object.get(parser_resp.body, ["values", "owner-info"], {})

          msg := sprintf(
            "support-group=%s,service=%s: %s %s declared with deprecated API version: %s (will break in k8s v%s)",
            [object.get(owner_info, "support-group", "none"), object.get(owner_info, "service", "none"), obj.kind, obj.metadata.name, obj.apiVersion, input.parameters.kubernetesVersion]
          )
        }

        violation[{"msg": msg}] {
          parser_resp.status_code != 200

          msg := "helm-manifest-parser did not return HTTP status 200. Please retry in ~5 minutes."
        }
