apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: gkhelm2releases
spec:
  crd:
    spec:
      names:
        kind: GkHelm2Releases

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package helm2releases

        iro := input.review.object

        violation[{"msg": msg}] {
          iro.kind == "ConfigMap"
          iro.metadata.labels.OWNER == "TILLER"
          msg := "deployed with an old Helm version"
        }
