apiVersion: v2
description: A Helm chart for the Opensearch stack
name: opensearch
version: 0.0.6
home: https://github.com/sapcc/helm-charts/tree/master/system/opensearch
dependencies:
  - name: opensearch
    alias: opensearch_master
    condition: opensearch_master.enabled
    repository: https://opensearch-project.github.io/helm-charts
    version: 2.6.2
  - name: opensearch
    alias: opensearch_client
    condition: opensearch_client.enabled
    repository: https://opensearch-project.github.io/helm-charts
    version: 2.6.2
  - name: opensearch
    alias: opensearch_data
    condition: opensearch_data.enabled
    repository: https://opensearch-project.github.io/helm-charts
    version: 2.6.2
  - name: opensearch-dashboards
    alias: opensearch_dashboards
    condition: opensearch_dashboards.enabled
    repository: https://opensearch-project.github.io/helm-charts
    version: 2.5.3
  - name: fluent
    repository: file://vendor/fluent
    version: 2.0.3
    condition: fluent.enabled
  - name: fluent-systemd
    alias: fluent_systemd
    repository: file://vendor/fluent-systemd
    version: 2.0.3
    condition: fluent_systemd.enabled
