owner-info:
  support-group: containers
  service: gatekeeper
  maintainers:
    - Stefan Majewsky
    - Falk Reimann
    - Sandro Jäckel
    - Muhammad Talal Anwar
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/gatekeeper

# documentation for this section: <https://github.com/open-policy-agent/gatekeeper/tree/master/charts/gatekeeper>
gatekeeper-upstream:
  createNamespace: false
  constraintViolationsLimit: 250
  logDenies: true
  disabledBuiltins: [] # do not disable `http.send`

  # We only use Gatekeeper for auditing, not as a validating webhook. Therefore
  # we don't need multiple replicas for the controller manager: It only needs
  # to validate templates and create/update/delete CRDs from them.
  disableValidatingWebhook: true
  # We also don't use it as a mutating webhook.
  disableMutation: true
  replicas: 1

  # We also don't need a strict pod disruption budget.
  pdb:
    controllerManager:
      minAvailable: 0

  # PodSecurityPolicy is disabled to enable upgrade to k8s 1.25+
  psp:
    enabled: false

  audit:
    resources:
      limits:
        cpu: 2
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 256Mi

  podLabels:
    alert-tier: k8s
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/targets: kubernetes

# Must be provided via --set-string; e.g. "qa-de-1" for QA controlplane or "s-qa-de-1" for QA scaleout. Tests will have the bogus value "t-qa-de-1".
cluster_name: null
# Must be provided via --set-string; e.g. "labs" or "qa" or "prod". Tests will have the bogus value "test".
cluster_layer: null
# Must be provided via --set-string; e.g. "baremetal" or "scaleout". Tests will have the bogus value "test".
cluster_type: null

gatekeeper_addons:
  image_tag: null # Must be provided via --set-string.

# NOTE: This section is shared with the `system/doop-central` chart.
doop:
  # values with default value null must be provided by values.yaml
  swift_region: null
  swift_password: null

# configuration for Tugger
use_tugger: false

tugger:
  createMutatingWebhook: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  rules:
    - pattern: '^docker\.elastic\.co/(.+)$'
      replacement: 'keppel.global.cloud.sap/ccloud-elastic-mirror/$1'

    - pattern: '^gcr\.io/(.+)$'
      replacement: 'keppel.global.cloud.sap/ccloud-gcr-mirror/$1'

    - pattern: '^k8s\.gcr\.io/(.+)$'
      replacement: 'keppel.global.cloud.sap/ccloud-k8sgcr-mirror/$1'

    - pattern: '^quay\.io/(.+)$'
      replacement: 'keppel.global.cloud.sap/ccloud-quay-mirror/$1'

    - pattern: '^registry\.opensource\.zalan\.do/(.+)$'
      replacement: 'keppel.global.cloud.sap/ccloud-zalando-mirror/$1'

    - pattern: '^(?:docker\.io/)?([^/]+)$'
      replacement: 'keppel.global.cloud.sap/ccloud-dockerhub-mirror/library/$1'

    - pattern: '^(?:docker\.io/)?([^/.]+/.+)$'
      replacement: 'keppel.global.cloud.sap/ccloud-dockerhub-mirror/$1'

    # enforcement is done by gatekeeper
    - pattern: '.*'
  whitelistNamespaces: []
