thanos:
  name: admin
  deployWholeThanos: false
  ingress:
    enabled: true
    hosts:
      - thanos-admin
  grpcIngress:
    enabled: true
    hosts:
      - thanos-admin
    # annotations:
      # ingress.kubernetes.io/protocol: h2c
      # ingress.kubernetes.io/ssl-redirect: "true"
  queryDiscovery: true
