thanos:
  name: admin
  deployWholeThanos: false
  ingress:
    enabled: true
    hosts:
      - thanos-admin
      - metrics.admin
  grpcIngress:
    enabled: false
    hosts:
      - thanos-admin
    annotations:
      ingress.kubernetes.io/protocol: h2c
      ingress.kubernetes.io/ssl-redirect: "true"
  queryDiscovery: true
  traefik:
    enabled: true
    route: 
      enabled: true
    hosts:
      - thanos-admin
