thanos:
  name: admin
  deployWholeThanos: false
  ingress:
    enabled: true
    hosts:
      - thanos-admin
  grpcIngress:
    enabled: true
    hosts:
      - thanos-admin
    annotations:
      kubernetes.io/ingress.class: nginx
  queryDiscovery: true
