{{- if .Values.scaleout.enabled }}
apiVersion: v1
kind: Secret

metadata:
  name: opensearch-certs

data:
  opensearchCA.crt: {{ required ".Values.ca.crt missing" .Values.ca.crt | b64enc | quote }}
  wildcard-tp-opensearch.pem: {{ required ".Values.tp.key missing" .Values.tp.pem | b64enc | quote }}
  wildcard-tp-opensearch.crt: {{ required ".Values.tp.crt missing" .Values.tp.crt | b64enc | quote }}
  admin.crt: {{ required ".Values.admin.crt missing" .Values.admin.crt | b64enc | quote }}
  admin.pem: {{ required ".Values.admin.pem missing" .Values.admin.pem | b64enc | quote }}
{{- end }}
