apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-bin
  labels:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: rabbitmq
data:
{{ (.Files.Glob "bin/*").AsConfig | indent 2 }}
  rabbitmq-configure: |
{{ include (print .Template.BasePath "/bin/_rabbitmq-configure.tpl") . | indent 4 }}
