apiVersion: v2
version: 1.0.1
name: octobus-query-exporter
description: Elasticsearch prometheus query exporter
maintainers:
  - name: Olaf Heydorn
  - name: Max Lendrich
dependencies:
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
