thanos:
  name: scaleout
  deployWholeThanos: false
  ingress:
    enabled: true
    hosts:
      - thanos-scaleout
      - metrics.scaleout
  grpcIngress:
    enabled: true
    hosts:
      - thanos-scaleout
  queryDiscovery: true
