# Might we worth building your own ipxe stack here: https://rom-o-matic.eu/
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ tuple . "db-migration" | include "ironic.job_name" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    system: openstack
    type: job
    component: ironic
spec:
  template:
    spec:
      initContainers:
      - name: "kubernetes-entrypoint"
        image: {{ .Values.global.registry }}/loci-ironic:{{ .Values.imageVersion }}
        imagePullPolicy: "IfNotPresent"
        command: ["kubernetes-entrypoint"]
        env:
        - name: "NAMESPACE"
          value: {{ .Release.Namespace | quote }}
        - name: "DEPENDENCY_SERVICE"
          value: "ironic-mariadb"
        - name: "COMMAND"
          value: "true"
      restartPolicy: OnFailure
      containers:
      - name: ironic-dbsync
        image: {{ .Values.global.registry }}/loci-ironic:{{ .Values.imageVersion }}
        imagePullPolicy: IfNotPresent
        command:
        - dumb-init
        - bash
        args:
        - -c
        - |
          {{- include "ironic.db_migration" . | indent 10 }}
        env:
        - name: PGAPPNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /etc/ironic
          name: etcironic
        - mountPath: /etc/ironic/ironic.conf
          name: ironic-etc
          subPath: ironic.conf
          readOnly: true
        - mountPath: /etc/ironic/policy.json
          name: ironic-etc
          subPath: policy.json
          readOnly: true
        - mountPath: /etc/ironic/rootwrap.conf
          name: ironic-etc
          subPath: rootwrap.conf
          readOnly: true
        - mountPath: /etc/ironic/logging.ini
          name: ironic-etc
          subPath: logging.ini
          readOnly: true
      volumes:
      - name: etcironic
        emptyDir: {}
      - name: ironic-etc
        configMap:
          name: ironic-etc
          defaultMode: 0444
