# Might we worth building your own ipxe stack here: https://rom-o-matic.eu/
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ironic_inspector_db_migration_name" . }}
  labels:
    system: openstack
    type: job
    component: ironic
spec:
  template:
    spec:
{{ include "utils.proxysql.job_pod_settings" . | indent 6 }}
      initContainers:
      - name: "kubernetes-entrypoint"
        image: {{ .Values.global.registry }}/loci-ironic:{{ .Values.imageVersion }}
        imagePullPolicy: "IfNotPresent"
        command: ["kubernetes-entrypoint"]
        env:
        - name: "NAMESPACE"
          value: {{ .Release.Namespace | quote }}
        - name: "DEPENDENCY_SERVICE"
{{- if eq .Values.mariadb.enabled true }}
          value: "ironic-mariadb"
{{- else }}
          value: "ironic-postgresql"
{{- end }}
        - name: "COMMAND"
          value: "true"
      restartPolicy: OnFailure
      containers:
      - name: dbsync
        image: {{ .Values.global.registry }}/loci-ironic:{{ .Values.imageVersion }}
        imagePullPolicy: IfNotPresent
        command:
        - dumb-init
        - bash
        args:
        - -c
        - |
          set -e
          trap "{{ include "utils.proxysql.proxysql_signal_stop_script" . | trim }}" EXIT
          ironic-inspector-dbsync upgrade
        env:
        - name: PGAPPNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /etc/ironic-inspector
          name: etcironicinspector
        - mountPath: /etc/ironic-inspector/ironic-inspector.conf
          name: ironic-inspector-etc
          subPath: ironic-inspector.conf
          readOnly: true
        - mountPath: /etc/ironic-inspector/policy.json
          name: ironic-etc
          subPath: policy.json
          readOnly: true
        - mountPath: /etc/ironic-inspector/rootwrap.conf
          name: ironic-etc
          subPath: rootwrap.conf
          readOnly: true
        - mountPath: /etc/ironic-inspector/logging.ini
          name: ironic-etc
          subPath: logging.ini
          readOnly: true
      volumes:
      - name: etcironicinspector
        emptyDir: {}
      - name: ironic-etc
        configMap:
          name: ironic-etc
          defaultMode: 0444
      - name: ironic-inspector-etc
        configMap:
          name: ironic-inspector-etc
          defaultMode: 0444
