# Might we worth building your own ipxe stack here: https://rom-o-matic.eu/
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ tuple . "security-group-setup" | include "ironic.job_name" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    system: openstack
    type: job
    component: ironic
spec:
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 0
      containers:
      - name: ironic-pxe-setup
        image: {{ .Values.global.registry }}/loci-ironic:{{ .Values.imageVersion }}
        imagePullPolicy: IfNotPresent
        command:
        - bash
        args:
        - -c
        - |
          {{- include "ironic.security_group_setup_script" . | indent 10 }}
        volumeMounts:
        - mountPath: /etc/ironic
          name: etcironic
        - mountPath: /etc/ironic/ironic.conf
          name: ironic-etc
          subPath: ironic.conf
          readOnly: true
      volumes:
      - name: etcironic
        emptyDir: {}
      - name: ironic-etc
        configMap:
          name: ironic-etc
          defaultMode: 0444

