thanos:
  name: kubernikus
  deployWholeThanos: false
  ingress:
    enabled: true
    hosts:
      - thanos-kubernikus
      - metrics.kubernikus
  grpcIngress:
    enabled: true
    hosts:
      - thanos-kubernikus
  queryDiscovery: true
